// prisma/seed.ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding exercises...')

  const exercises = [
    // ── MOBILITY ──────────────────────────────────────────
    {
      name: 'Rotation cervicale',
      category: 'mobility' as const,
      description: 'Rotation lente de la tête gauche-droite en position assise, menton parallèle au sol.',
      defaultSets: 2,
      defaultReps: 10,
      defaultDuration: 0,
      pathologies: ['Cervicalgie', 'Spondylarthrite'],
      tags: ['cou', 'cervical'],
    },
    {
      name: 'Flexion cervicale latérale',
      category: 'mobility' as const,
      description: 'Inclinaison de la tête vers l\'épaule, oreille vers l\'épaule sans soulever celle-ci.',
      defaultSets: 2,
      defaultReps: 8,
      defaultDuration: 0,
      pathologies: ['Cervicalgie'],
      tags: ['cou', 'cervical', 'étirement'],
    },
    {
      name: 'Mobilisation thoracique en rotation',
      category: 'mobility' as const,
      description: 'Assis sur une chaise, mains croisées sur les épaules, rotation du tronc gauche et droite.',
      defaultSets: 3,
      defaultReps: 10,
      defaultDuration: 0,
      pathologies: ['Lombalgie chronique', 'Spondylarthrite'],
      tags: ['dos', 'thoracique'],
    },
    {
      name: 'Étirement ischio-jambiers debout',
      category: 'mobility' as const,
      description: 'Jambe allongée sur une surface surélevée, flexion avant du buste, dos droit.',
      defaultSets: 2,
      defaultReps: 0,
      defaultDuration: 30,
      pathologies: ['Lombalgie chronique', 'Tendinopathie rotulienne'],
      tags: ['cuisse', 'ischio'],
    },
    {
      name: 'Mobilisation de cheville en cercles',
      category: 'mobility' as const,
      description: 'Assis, pied soulevé, dessiner des grands cercles avec le pied dans les deux sens.',
      defaultSets: 2,
      defaultReps: 10,
      defaultDuration: 0,
      pathologies: ['Entorse de cheville', 'Post-opératoire genou'],
      tags: ['cheville', 'pied'],
    },
    {
      name: 'Flexion-extension de genou passif',
      category: 'mobility' as const,
      description: 'Assis au bord de la table, laisser le genou fléchir et s\'étendre par gravité, en douceur.',
      defaultSets: 3,
      defaultReps: 15,
      defaultDuration: 0,
      pathologies: ['Gonarthrose', 'Post-opératoire genou'],
      tags: ['genou'],
    },
    {
      name: 'Étirement du piriforme',
      category: 'mobility' as const,
      description: 'Allongé sur le dos, cheville posée sur le genou opposé, tirer la cuisse vers soi.',
      defaultSets: 2,
      defaultReps: 0,
      defaultDuration: 30,
      pathologies: ['Lombalgie chronique', 'Arthrose de hanche'],
      tags: ['hanche', 'fessier'],
    },
    {
      name: 'Circumduction de hanche',
      category: 'mobility' as const,
      description: 'Debout, un pied soulevé, dessiner des grands cercles avec le genou.',
      defaultSets: 2,
      defaultReps: 8,
      defaultDuration: 0,
      pathologies: ['Arthrose de hanche'],
      tags: ['hanche'],
    },

    // ── STRENGTHENING ────────────────────────────────────
    {
      name: 'Gainage ventral',
      category: 'strengthening' as const,
      description: 'Position planche sur les avant-bras, corps aligné, maintien en isométrique.',
      defaultSets: 3,
      defaultReps: 0,
      defaultDuration: 30,
      pathologies: ['Lombalgie chronique', 'Hernie discale'],
      tags: ['abdominaux', 'core', 'isométrique'],
    },
    {
      name: 'Pont fessier',
      category: 'strengthening' as const,
      description: 'Allongé sur le dos, pieds à plat, soulever le bassin jusqu\'à l\'alignement épaules-hanches-genoux.',
      defaultSets: 3,
      defaultReps: 12,
      defaultDuration: 0,
      pathologies: ['Lombalgie chronique', 'Post-AVC'],
      tags: ['fessier', 'lombaires'],
    },
    {
      name: 'Squat au mur (Wall squat)',
      category: 'strengthening' as const,
      description: 'Dos contre le mur, glisser en position chaise (90°) et maintenir.',
      defaultSets: 3,
      defaultReps: 0,
      defaultDuration: 30,
      pathologies: ['Gonarthrose', 'Tendinopathie rotulienne', 'Syndrome fémoro-patellaire'],
      tags: ['quadriceps', 'genou', 'isométrique'],
    },
    {
      name: 'Élévation de jambe tendue',
      category: 'strengthening' as const,
      description: 'Allongé, une jambe fléchie, soulever l\'autre jambe tendue à 45° lentement.',
      defaultSets: 3,
      defaultReps: 15,
      defaultDuration: 0,
      pathologies: ['Gonarthrose', 'Syndrome fémoro-patellaire'],
      tags: ['quadriceps', 'hanche'],
    },
    {
      name: 'Abduction de hanche avec élastique',
      category: 'strengthening' as const,
      description: 'Debout, élastique autour des chevilles, écarter la jambe vers l\'extérieur lentement.',
      defaultSets: 3,
      defaultReps: 12,
      defaultDuration: 0,
      pathologies: ['Arthrose de hanche', 'Gonarthrose'],
      tags: ['hanche', 'abducteurs', 'élastique'],
    },
    {
      name: 'Travail du trapèze en Y',
      category: 'strengthening' as const,
      description: 'Allongé ventre, bras écartés en Y, soulever légèrement les bras en pinçant les omoplates.',
      defaultSets: 3,
      defaultReps: 12,
      defaultDuration: 0,
      pathologies: ['Épaule douloureuse', 'Cervicalgie'],
      tags: ['épaule', 'trapèze', 'omoplate'],
    },
    {
      name: 'Rotation externe d\'épaule avec élastique',
      category: 'strengthening' as const,
      description: 'Coude plié à 90° contre le corps, rotation externe contre la résistance de l\'élastique.',
      defaultSets: 3,
      defaultReps: 15,
      defaultDuration: 0,
      pathologies: ['Épaule douloureuse'],
      tags: ['épaule', 'coiffe', 'élastique'],
    },
    {
      name: 'Flexion plantaire sur marche',
      category: 'strengthening' as const,
      description: 'Debout sur une marche, monter sur la pointe des pieds lentement, descendre en contrôle.',
      defaultSets: 3,
      defaultReps: 15,
      defaultDuration: 0,
      pathologies: ['Entorse de cheville', 'Tendinopathie rotulienne'],
      tags: ['cheville', 'mollet', 'excentrique'],
    },
    {
      name: 'Gainage latéral',
      category: 'strengthening' as const,
      description: 'Allongé sur le côté, appui sur l\'avant-bras, soulever le bassin en ligne droite.',
      defaultSets: 3,
      defaultReps: 0,
      defaultDuration: 20,
      pathologies: ['Lombalgie chronique', 'Spondylarthrite'],
      tags: ['core', 'obliques', 'isométrique'],
    },
    {
      name: 'Step-up',
      category: 'strengthening' as const,
      description: 'Monter et descendre d\'une marche ou d\'un step, en contrôlant la descente.',
      defaultSets: 3,
      defaultReps: 12,
      defaultDuration: 0,
      pathologies: ['Post-opératoire genou', 'Syndrome fémoro-patellaire'],
      tags: ['genou', 'quadriceps', 'fonctionnel'],
    },

    // ── CARDIO ────────────────────────────────────────────
    {
      name: 'Marche sur place',
      category: 'cardio' as const,
      description: 'Marche sur place en levant bien les genoux, rythme modéré.',
      defaultSets: 1,
      defaultReps: 0,
      defaultDuration: 120,
      pathologies: ['Post-AVC', 'Lombalgie chronique', 'Arthrose de hanche'],
      tags: ['marche', 'endurance'],
    },
    {
      name: 'Vélo stationnaire',
      category: 'cardio' as const,
      description: 'Pédalage en résistance légère, cadence régulière, sans douleur au genou.',
      defaultSets: 1,
      defaultReps: 0,
      defaultDuration: 600,
      pathologies: ['Gonarthrose', 'Post-opératoire genou'],
      tags: ['vélo', 'endurance', 'genou'],
    },
    {
      name: 'Montées de genoux assis',
      category: 'cardio' as const,
      description: 'Assis sur une chaise stable, alterner les levées de genoux à rythme soutenu.',
      defaultSets: 3,
      defaultReps: 0,
      defaultDuration: 30,
      pathologies: ['Post-AVC', 'Lombalgie chronique'],
      tags: ['hanche', 'endurance', 'assis'],
    },
    {
      name: 'Pas chassés latéraux',
      category: 'cardio' as const,
      description: 'Déplacements latéraux droite-gauche sur 2-3 mètres, rythme modéré.',
      defaultSets: 3,
      defaultReps: 0,
      defaultDuration: 30,
      pathologies: ['Entorse de cheville', 'Post-AVC'],
      tags: ['coordination', 'cardio', 'latéral'],
    },

    // ── BALANCE ───────────────────────────────────────────
    {
      name: 'Appui unipodal',
      category: 'balance' as const,
      description: 'Tenir en équilibre sur un pied, regard fixe, mains disponibles pour rattrapage.',
      defaultSets: 3,
      defaultReps: 0,
      defaultDuration: 20,
      pathologies: ['Entorse de cheville', 'Post-AVC', 'Post-opératoire genou'],
      tags: ['équilibre', 'proprioception', 'cheville'],
    },
    {
      name: 'Appui unipodal sur mousse',
      category: 'balance' as const,
      description: 'Même exercice sur un coussin instable ou tapis de mousse pour augmenter la difficulté.',
      defaultSets: 3,
      defaultReps: 0,
      defaultDuration: 20,
      pathologies: ['Entorse de cheville', 'Gonarthrose'],
      tags: ['équilibre', 'proprioception', 'avancé'],
    },
    {
      name: 'Marche talon-pointe',
      category: 'balance' as const,
      description: 'Marcher en ligne droite en posant talon puis pointe devant l\'autre pied.',
      defaultSets: 2,
      defaultReps: 10,
      defaultDuration: 0,
      pathologies: ['Post-AVC', 'Entorse de cheville'],
      tags: ['équilibre', 'marche', 'coordination'],
    },
    {
      name: 'Transfert de poids debout',
      category: 'balance' as const,
      description: 'Debout, pieds largeur d\'épaules, transférer le poids d\'un côté à l\'autre lentement.',
      defaultSets: 2,
      defaultReps: 10,
      defaultDuration: 0,
      pathologies: ['Post-AVC', 'Arthrose de hanche'],
      tags: ['équilibre', 'proprioception'],
    },
    {
      name: 'Debout sur plateau instable',
      category: 'balance' as const,
      description: 'Maintenir l\'équilibre sur un plateau de proprioception, d\'abord bipodal.',
      defaultSets: 3,
      defaultReps: 0,
      defaultDuration: 30,
      pathologies: ['Entorse de cheville', 'Syndrome fémoro-patellaire'],
      tags: ['proprioception', 'plateau', 'avancé'],
    },

    // ── BREATHING ─────────────────────────────────────────
    {
      name: 'Respiration diaphragmatique',
      category: 'breathing' as const,
      description: 'Allongé, une main sur le ventre, inspirer en gonflant l\'abdomen, expirer lentement.',
      defaultSets: 1,
      defaultReps: 0,
      defaultDuration: 120,
      pathologies: ['Post-AVC', 'Spondylarthrite', 'Lombalgie chronique'],
      tags: ['respiration', 'relaxation', 'diaphragme'],
    },
    {
      name: 'Respiration en cohérence cardiaque',
      category: 'breathing' as const,
      description: 'Inspirer 5 secondes, expirer 5 secondes, maintenir un rythme régulier pendant 5 minutes.',
      defaultSets: 1,
      defaultReps: 0,
      defaultDuration: 300,
      pathologies: ['Post-AVC', 'Spondylarthrite'],
      tags: ['respiration', 'relaxation', 'cohérence'],
    },
    {
      name: 'Drainage postural',
      category: 'breathing' as const,
      description: 'Position déclive adaptée à la zone à drainer, toux contrôlée pour expectoration.',
      defaultSets: 1,
      defaultReps: 0,
      defaultDuration: 180,
      pathologies: ['Post-opératoire genou'],
      tags: ['drainage', 'respiration', 'postural'],
    },
    {
      name: 'Expansion thoracique latérale',
      category: 'breathing' as const,
      description: 'Main posée sur le flanc, inspirer en poussant la main vers l\'extérieur, expirer lentement.',
      defaultSets: 2,
      defaultReps: 8,
      defaultDuration: 0,
      pathologies: ['Spondylarthrite', 'Post-AVC'],
      tags: ['thoracique', 'respiration', 'expansion'],
    },
  ]

  for (const exercise of exercises) {
    await prisma.exercise.upsert({
      where: { name: exercise.name },
      update: exercise,
      create: exercise,
    })
  }

  console.log(`✅ ${exercises.length} exercises seeded.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
